const id = {
  recognition: {
    short: "Juara 2 · PIDI DIGDAYA x Hackathon",
    rank: "Juara 2",
    event: "PIDI DIGDAYA x Hackathon",
    organizer: "Diselenggarakan oleh Bank Indonesia",
    description: "YUDHA meraih Juara 2 dalam PIDI DIGDAYA x Hackathon. Pencapaian ini menjadi salah satu tonggak perjalanan kami membangun pengalaman belajar untuk persiapan karier.",
    program: "Tentang program PIDI",
    catalog: "Lihat katalog BI Innovation Hub",
    catalogNote: "YUDHA juga tercantum dalam katalog inovasi resmi PIDI sebagai bagian dari Top 80.",
  },
  traction: {
    label: "Pencapaian & bukti produk",
    title: "Dari ide menjadi produk yang bisa dicoba.",
    description: "Didirikan pada Maret 2026, YUDHA terus berkembang menjadi produk yang bisa dicoba. Lihat pencapaian kami, unduh aplikasinya, dan kenali pengalaman belajarnya lewat demo produk.",
    downloads: "Download di Google Play",
    latestUpdate: "Pembaruan aplikasi di Google Play",
    source: "Sumber: Google Play",
    checked: "Diperiksa 10 Oktober 2026",
    downloadsNote: "Angka unduhan adalah rentang publik Google Play, bukan jumlah pengguna aktif.",
    productTitle: "Jelajahi YUDHA secara langsung",
    productDescription: "Aplikasi, demo, dan komunitas tersedia untuk kamu yang ingin mengenal YUDHA lebih dekat.",
    milestones: [
      { title: "Tersedia di Google Play", description: "Unduh aplikasi Android dan coba pengalaman belajar YUDHA.", action: "Buka Google Play" },
      { title: "Demo produk publik", description: "Lihat alur latihan, duel PvP, progres, dan AI Interview dalam video demo.", action: "Tonton demo" },
      { title: "Komunitas pengguna", description: "Terhubung dengan komunitas YUDHA untuk berdiskusi dan memberikan masukan.", action: "Gabung WhatsApp" },
    ],
  },
  profile: {
    label: "Profil startup",
    title: "Tim kecil, fokus pada persiapan karier.",
    description: "YUDHA — Your Ultimate Digital Hiring Arena — didirikan pada Maret 2026 oleh empat co-founder dengan fokus pada produk, teknologi, dan pengembangan bisnis.",
    founders: "Co-founder",
    market: "Fokus pasar",
    marketValue: "Indonesia",
    contact: "Kontak bisnis",
    contactDescription: "Untuk kemitraan, pertanyaan program startup, media, atau diskusi produk.",
    recognition: "Pencapaian",
    viewTraction: "Lihat pencapaian & bukti produk",
  },
};

const en: typeof id = {
  recognition: {
    short: "2nd Place · PIDI DIGDAYA x Hackathon",
    rank: "2nd Place",
    event: "PIDI DIGDAYA x Hackathon",
    organizer: "Organized by Bank Indonesia",
    description: "YUDHA earned 2nd Place at PIDI DIGDAYA x Hackathon. This achievement marks a milestone in our journey to build a learning experience for career preparation.",
    program: "About the PIDI program",
    catalog: "View the BI Innovation Hub catalog",
    catalogNote: "YUDHA is also listed in PIDI's official innovation catalog as part of the Top 80.",
  },
  traction: {
    label: "Milestones & product evidence",
    title: "From an idea to a product you can try.",
    description: "Founded in March 2026, YUDHA continues to grow into a product you can try. Explore our milestones, download the app, and see the learning experience in our product demo.",
    downloads: "Downloads on Google Play",
    latestUpdate: "Latest Google Play app update",
    source: "Source: Google Play",
    checked: "Checked October 10, 2026",
    downloadsNote: "The download count is Google Play's public range, not an active user count.",
    productTitle: "Explore YUDHA firsthand",
    productDescription: "Our app, demo, and community are available for anyone who wants to get to know YUDHA.",
    milestones: [
      { title: "Available on Google Play", description: "Download the Android app and try YUDHA's learning experience.", action: "Open Google Play" },
      { title: "Public product demo", description: "See practice sessions, PvP duels, progress insights, and AI Interview in our demo video.", action: "Watch demo" },
      { title: "User community", description: "Connect with the YUDHA community to discuss the product and share feedback.", action: "Join WhatsApp" },
    ],
  },
  profile: {
    label: "Startup profile",
    title: "A small team focused on career preparation.",
    description: "YUDHA — Your Ultimate Digital Hiring Arena — was founded in March 2026 by four co-founders working across product, technology, and business development.",
    founders: "Co-founders",
    market: "Market focus",
    marketValue: "Indonesia",
    contact: "Business contact",
    contactDescription: "For partnerships, startup program inquiries, media, or product conversations.",
    recognition: "Recognition",
    viewTraction: "Explore milestones & product evidence",
  },
};

export const startupCopy = { id, en };
